### ISSUE TITLE
TestRemote_nsmgr_restart.TestHeal/TestRemote_nsmgr_restart is unstable

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-packet#166]
https://github.com/networkservicemesh/integration-k8s-packet/pull/165/checks?check_run_id=4250005757

**Comment by edwarnicke** [comment]
@glazychev-art Here's another instance https://github.com/networkservicemesh/integration-k8s-packet/pull/174/checks?check_run_id=4294155952
