### ISSUE TITLE
Observability test is unstable

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/integration-k8s-packet#242]
## Run
https://github.com/networkservicemesh/integration-k8s-packet/runs/5283914265?check_suite_focus=true

## Log
[container-logs.zip](https://github.com/networkservicemesh/integration-k8s-packet/files/8117645/container-logs.zip)
[ci-logs.zip](https://github.com/networkservicemesh/integration-k8s-packet/files/8117647/ci-logs.zip)

**Comment by denis-tingaikin** [comment]
The issue is not reproducing yet.
