### ISSUE TITLE
The first run of SriovKernel2Noop test is unstable

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/integration-k8s-packet#320]
### Description

For some reason, it takes a very long time to set up the datapath for the first run of the SriovKernel2Noop.
Requests are working fine. 
After the Request, we run a livelinesschecker that pings the endpoint. But since the datapath is not ready, this leads to healing, which now constantly calls Close/Request. Because of this, we cannot create a connection at all.

Turned off this check for a while to look at ci - https://github.com/networkservicemesh/deployments-k8s/pull/8788

**Comment by glazychev-art** [comment]
#### Current state

How it worked in previous releases:
\- establishing a connection for SriovKernelNoop also took a long time, but then forwarder-vpp turned on by mistake and Sriov mechanisms were not involved. So, it worked as Kernel2Vxlan2Kernel
This bug was fixed in 1.8.0

Checked:
1. Running the test [in the current form](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/SriovKernel2Noop) - does not work (this is what you need to figure out)
2. Disable LivelinessChecker - ping starts working after some time. This is a workaround for now.
3. Restart the test: SriovKernelNoop after SriovKernelNoop - does not work
4. Restart the test: SriovKernelNoop after Vfio2Noop - works without delay
5. Deploy the [ponger](https://github.com/networkservicemesh/deployments-k8s/tree/main/apps/nsc-kernel-ponger) first, and then the client - works without delay
6. If, after the ping starts working, we introduce violations on the side of the ponger (set the interface down) - the ping does not start working again even after set the interface up.
7. Manual configuration. The first server has a virtual function that uses the kernel driver. The second is configured as a ponger - works without delay


At the moment, this problem looks like that after an attempt to heal (close) we somehow incorrectly return (restore) the virtual function to the server side.

**Comment by glazychev-art** [comment]
8. Manual configuration. Inject a VF to the pod manually. The second is configured as a ponger - works without delay
9. **a**. `dmesg` logs in case of simple Close() (no healing):
```
[10761.672271] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[10761.672402] IPv6: ADDRCONF(NETDEV_CHANGE): calib67fef27028: link becomes ready
[10768.941673] iavf 0000:8a:19.0: enabling device (0000 -> 0002)
[10769.012997] iavf 0000:8a:19.0: Invalid MAC address 00:00:00:00:00:00, using random
[10769.013261] iavf 0000:8a:19.0: Multiqueue Enabled: Queue pair count = 4
[10769.013667] iavf 0000:8a:19.0: MAC address: 86:ee:3b:26:b6:97
[10769.013671] iavf 0000:8a:19.0: GRO is enabled
[10769.017860] iavf 0000:8a:19.0 ens6f3v0: renamed from eth0
[10769.110078] iavf 0000:8a:19.0 nsm-1: renamed from ens6f3v0
[10769.229324] iavf 0000:8a:19.0 nsm-1: NIC Link is Up Speed is 25 Gbps Full Duplex
[10769.229347] IPv6: ADDRCONF(NETDEV_CHANGE): nsm-1: link becomes ready
[10791.747276] iavf 0000:8a:19.0 ens6f3v0: renamed from nsm-1
```
9. **b**. `dmesg` logs in case of healing:
```
[ 8020.309562] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 8020.309668] IPv6: ADDRCONF(NETDEV_CHANGE): calia3bb69036f3: link becomes ready
[ 8028.422319] iavf 0000:8a:19.0: enabling device (0000 -> 0002)
[ 8028.492292] iavf 0000:8a:19.0: Invalid MAC address 00:00:00:00:00:00, using random
[ 8028.492603] iavf 0000:8a:19.0: Multiqueue Enabled: Queue pair count = 4
[ 8028.493129] iavf 0000:8a:19.0: MAC address: 96:c7:84:bf:a9:27
[ 8028.493134] iavf 0000:8a:19.0: GRO is enabled
[ 8028.499188] iavf 0000:8a:19.0 ens6f3v0: renamed from eth0
[ 8028.589131] iavf 0000:8a:19.0 nsm-1: renamed from ens6f3v0
[ 8028.720561] iavf 0000:8a:19.0 nsm-1: NIC Link is Up Speed is 25 Gbps Full Duplex
[ 8028.720593] IPv6: ADDRCONF(NETDEV_CHANGE): nsm-1: link becomes ready
[ 8030.539703] iavf 0000:8a:19.0 ens6f3v0: renamed from nsm-1
[ 8030.553035] ice 0000:8a:00.3: MAC 33:33:ff:de:c6:45 does not exist for VF 0
[ 8030.857268] iavf 0000:8a:19.0 nsm-1: renamed from ens6f3v0
[ 8030.976677] iavf 0000:8a:19.0 nsm-1: NIC Link is Up Speed is 25 Gbps Full Duplex
[ 8030.976705] IPv6: ADDRCONF(NETDEV_CHANGE): nsm-1: link becomes ready
[ 8032.752744] iavf 0000:8a:19.0 ens6f3v0: renamed from nsm-1
[ 8032.760535] ice 0000:8a:00.3: MAC 76:38:5b:de:c6:45 does not exist for VF 0
[ 8032.769228] ice 0000:8a:00.3: MAC 33:33:ff:de:c6:45 does not exist for VF 0
```

**Comment by denis-tingaikin** [comment]
Closed by https://github.com/networkservicemesh/deployments-k8s/pull/8919
