### ISSUE TITLE
SRIOV tests are unstable

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-packet#325]

**Comment by denis-tingaikin** [comment]
@glazychev-art please add description/prs

**Comment by glazychev-art** [comment]
Sometimes random vfio tests failed.
Incident:
https://github.com/networkservicemesh/integration-k8s-packet/actions/runs/4224905945/jobs/7336468169

These PRs fixed the problem:
- https://github.com/networkservicemesh/sdk-sriov/pull/497
- https://github.com/networkservicemesh/sdk-sriov/pull/507
- https://github.com/networkservicemesh/cmd-forwarder-sriov/pull/590
- https://github.com/networkservicemesh/integration-k8s-packet/pull/322

**Comment by denis-tingaikin** [comment]
@glazychev-art Thanks!
