### ISSUE TITLE
Packet reaches resources limits

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/integration-k8s-packet#50]
## Description
We have only 3 packet clusters (6 servers) available for automation. Every CI run takes ~20-40 minutes to setup cluster and ~15-20 minutes to run all tests. If there are >3 automation requests/hour, all subsequent requests start failing with `Error: empty hardware reservations list`.

## Possible solutions
1. Start waiting for free servers in `cloudtest`. Right now it is just trying to pick 2 servers and returns an error if it fails.
   * pros
      1. We are testing every automation request.
   * cons
      1. It can be hard to avoid starvation for multiple CI requests, because each of them tries to pick 2 servers one-by-one and it looks like there is no way to add some global synchronization for them.
2. Don't run another automation request if we already have 1 (2, 3 ?) running and just stack them to the single one (instead of creating a queue).
   * pros
      1. There definitely will be no starvation.
   * cons
      1. We are testing not every single automation request, but packs of automation requests.

**Comment by edwarnicke** [comment]
@Bolodya1997 Is this related to not having enough reserve instances setup for SRIOV for the flow of testing we have?  Ideally how may would we want?

**Comment by Bolodya1997** [comment]
> @Bolodya1997 Is this related to not having enough reserve instances setup for SRIOV for the flow of testing we have? Ideally how may would we want?

We are OK with the count of the reserve instances we have. Currently we have some troubles with CI spawning too much events from `integration-k8s-kind`, so it shouldn't be an issue when it would be fixed.

But I guess that (probably not now, but sometime in future) we should think about making a queue of events, because it looks like a more scalable way than blindly increasing the count of automation servers, because we really don't need all of these servers to use them all the time.

**Comment by edwarnicke** [comment]
@Bolodya1997 OK... so is this *currently* working or broken?

**Comment by Bolodya1997** [comment]
Packet is working now, but the problem with overspawning events is still there.

**Comment by Mixaster995** [comment]
@edwarnicke 3 clusters is enough for this moment, we don't see an issue with this. Can we close this?

**Comment by glazychev-art** [comment]
Reworked the cluster setup, now servers are allocated on demand.
