### ISSUE TITLE
Packet setup is unstable

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/integration-k8s-packet#56]
## Description
During the packet cluster setup we need to reboot servers to enable SR-IOV on them. Sometimes for some reason server fails to start after the reboot.

**Comment by Bolodya1997** [comment]
Currently it is not so clear what is the reason, so I am communicating with the packet support team.

**Comment by Bolodya1997** [comment]
Ticket created: https://support.equinixmetal.com/hc/en-us/requests/12702

**Comment by vielmetti** [comment]
We are aware of an issue that has affected UEFI systems (not BIOS) systems with Ubuntu and GRUB. There's a writeup at https://gist.github.com/vielmetti/dafb5128ef7535c218f6d963c5bc624e - I don't *think* this affects you, but worth a look.

**Comment by Bolodya1997** [comment]
> We are aware of an issue that has affected UEFI systems (not BIOS) systems with Ubuntu and GRUB. There's a writeup at https://gist.github.com/vielmetti/dafb5128ef7535c218f6d963c5bc624e - I don't _think_ this affects you, but worth a look.

Thank you, we will try such fix. But I am afraid that this is some other issue, because we are always using fresh setups.

**Comment by Bolodya1997** [comment]
The issue is still active, reopened the ticket: https://support.equinixmetal.com/hc/en-us/requests/14125.

**Comment by edwarnicke** [comment]
@vielmetti Could you help us out with getting our ticket reopened here?

**Comment by vielmetti** [comment]
Equinix Metal has identified a hardware issue (BIOS configuration) that would explain the problem as presented, and we've corrected that problem on one machine. The next round of work is verifying this configuration option on the rest of the fleet. Thanks @Bolodya1997 for the detailed descriptions which helped us track this down.

**Comment by vielmetti** [comment]
Several servers in the rest of the fleet have had BIOS configuration changes, which should correct the problems as described. Please report any issues that you see!

**Comment by Bolodya1997** [comment]
Looks like it is no more reproducible after the BIOS fix, closing this issue.
